arb-dir: lib/l10n
template-arb-file: app_tr.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
output-dir: lib/generated/l10n