// lib/constants/region.dart

// Main regions
const List<String> mainRegions = [
  "Gazimağusa",
  "Girne", 
  "Güzelyurt",
  "İskele",
  "Lefke",
  "Lefkoşa",
];

// Regional hierarchy mapping
const Map<String, List<String>> regionHierarchy = {
  "Lefkoşa": [
    "Akıncılar",
    "Alayköy", 
    "Arabahmet",
    "Balıkesir",
    "Beyköy",
    "Cihangir",
    "Cyprus Internation University (CIU)",
    "Çağlayan",
    "Çukurova",
    "Değirmenlik",
    "Demirhan",
    "Dereboyu",
    "Dikmen",
    "Dilekkaya",
    "Düzova",
    "Ercan",
    "Erdemli",
    "Gayretköy",
    "Gaziler",
    "Gaziköy",
    "Göçmenköy",
    "Gökhan",
    "Gönyeli",
    "Gürpınar",
    "Hamitköy",
    "Haspolat",
    "İkidere",
    "Kalavaç",
    "Kanlıköy",
    "Kargı",
    "Kırıkkale",
    "Kırklar",
    "Kızılbaş",
    "Köşklüçiftlik",
    "Kumsal",
    "Küçük Kaymaklı",
    "Marmara",    
    "Meriç",
    "Metehan (Kermia)",
    "Minareliköy",
    "Near East University (NEU)",
    "Ortaköy",
    "Suriçi",
    "Taşkınköy",
    "Terminal",
    "Türkeli",
    "Yeniceköy",
    "Yenikent",
    "Yenişehir",
    "Yılmazköy",
    "Yiğitler",
  ],
  
  "Gazimağusa": [
  "Akdoğan",
  "Akova",
  "Alaniçi",
  "Arıdamı",
  "Aslanköy",
  "Atlılar",
  "Baykal",
  "Beyarmudu",
  "Canbulat",
  "Çamlıca",
  "Çanakkale",
  "Çayönü",
  "Çınarlı",
  "DAÜ",
  "Derinya",
  "Dörtyol",
  "Dumlupınar",
  "Düzce",
  "Ergenekon",
  "Geçitkale",
  "Glapsides",
  "Gönendere",
  "Görneç",
  "Gülseren",
  "Güvercinlik",
  "İncirli",
  "İnönü",
  "Kaliland",
  "Karakol",
  "Korkuteli",
  "Köprülü",
  "Kurudere",
  "Mallıdağ",
  "Maraş",
  "Mormenekşe",
  "Muratağa",
  "Mutluyaka",
  "Nergisli",
  "Palm Beach",
  "Paşaköy",
  "Pile",
  "Pınarlı",
  "Pirhan",
  "Sakarya",
  "Saklıkent Area",
  "Sandallar",
  "Serdarlı",
  "Sosyal Konutlar (DAÜ Yanı)",
  "Sosyal Konutlar Apartmanlar",
  "Suriçi",
  "Sütlüce",
  "Tatlısu",
  "Tekant",
  "Tirmen",
  "Turunçlu",
  "Tuzla",
  "Türkmenköy",
  "Ulukışla",
  "Vadili",
  "Yamaçköy",
  "Yeniboğaziçi",
  "Yıldırım",
],
  
  "Girne": [
    "Ağırdağ",
    "Akçiçek",
    "Akdeniz",
    "Alemdağ",
    "Alsancak",
    "Arapköy",
    "Aşağı Dikmen",
    "Aşağı Taşkent",
    "Bahçeli",
    "Bellapais",
    "Beşparmak",
    "Beylerbeyi",
    "Boğazköy",
    "Çamlıbel",
    "Çatalköy",
    "Dağyolu",
    "Doğanköy",
    "Edremit",
    "Esentepe",
    "Girne American University",
    "Geçitköy",
    "Girne Merkez",
    "Aşağı Girne",
    "Göçeri",
    "Güngör",
    "Hisarköy",
    "Ilgaz",
    "İncesu",
    "Karaağaç",
    "Karakum",
    "Karaman",
    "Karmi",
    "Karaoğlanoğlu",
    "Karpaşa",
    "Karşıyaka",
    "Kayalar",
    "Kılıçaslan",
    "Koruçam",
    "Kozan",
    "Kömürcü",
    "Lapta",
    "Malatya",
    "Ozanköy",
    "Özhan",
    "Pınarbaşı",
    "Sadrazamköy",
    "Şirinevler",
    "Tepebaşı",
    "Yeşiltepe",
    "Yukarı Dikmen",
    "Yukarı Taşkent",
    "Zeytinlik",
  ],
  
  "Güzelyurt": [
    "Akçay",
    "Aşağı Bostancı",
    "Aydınköy",
    "Gayretköy",
    "Güneşköy",
    "Güzelyurt",
    "Kalkanlı",
    "Mevlevi",
    "Serhatköy",
    "Şahinler",
    "Yayla",
    "Yukarı Bostancı",
    "Yuvacık",
    "Zümrütköy",
  ],
  
  "İskele": [
    "Adaçay",
    "Ağıllar",
    "Altınova",
    "Ardahan",
    "Avtepe",
    "Aygün",
    "Bafra",
    "Balalan",
    "Boğaz",
    "Boğaziçi",
    "Boğaztepe",
    "Boltaşlı",
    "Büyükkonuk",
    "Çayırova",
    "Derince",
    "Dipkarpaz",
    "Ergazi",
    "Esenköy",
    "Gelincik",
    "İskele Bahçeler",
    "İskele Merkez",
    "Kaleburnu",
    "Kalecik",
    "Kantara",
    "Kaplıca",
    "Kilitkaya",
    "Kumyalı",
    "Kurtuluş",
    "Kuruova",
    "Kuzucuk",
    "Long Beach",
    "Mehmetçik",
    "Mersinlik",
    "Ötüken",
    "Pamuklu",
    "Sazlıköy",
    "Sınırüstü",
    "Sipahi",
    "Taşlıca",
    "Topçuköy",
    "Turnalar",
    "Tuzluca",
    "Yarköy",
    "Yedikonuk",
    "Yeni Erenköy",
    "Yeşilköy",
    "Zeybekköy",
    "Ziyamet",
  ],
  
  "Lefke": [
    "Aplıç",
    "Bademliköy",
    "Bağlıköy",
    "Cengizköy",
    "Çamlıköy",
    "Denizli",
    "Doğancı",
    "Erenköy",
    "Gaziveren",
    "Gemikonağı",
    "Günebakan",
    "Kurutepe",
    "Lefke",
    "Madenliköy",
    "Ömerli",
    "Şirinköy",
    "Taşköy",
    "Taşpınar",
    "Yedidalga",
    "Yeşilırmak",
    "Yeşilyurt",
  ],
};

// Flattened list of all regions (main + sub) sorted alphabetically
const List<String> allRegionsList = [
  "Adaçay",
  "Ağıllar", 
  "Ağırdağ",
  "Akçay",
  "Akçiçek",
  "Akdeniz",
  "Akdoğan",
  "Akıncılar",
  "Akova",
  "Alaniçi",
  "Alayköy",
  "Alemdağ",
  "Alsancak",
  "Altınova",
  "Aplıç",
  "Arapköy",
  "Ardahan",
  "Arıdamı",
  "Aşağı Bostancı",
  "Aşağı Dikmen",
  "Aşağı Taşkent",
  "Aslanköy",
  "Atlılar",
  "Avtepe",
  "Aydınköy",
  "Aygün",
  "Bademliköy",
  "Bafra",
  "Bağlıköy",
  "Bahçeli",
  "Balalan",
  "Balıkesir",
  "Baykal",
  "Beşparmak",
  "Beyarmudu",
  "Beyköy",
  "Beylerbeyi",
  "Boğaz",
  "Boğaziçi",
  "Boğazköy",
  "Boğaztepe",
  "Boltaşlı",
  "Büyükkonuk",
  "Cengizköy",
  "Cihangir",
  "Çamlıbel",
  "Çamlıca",
  "Çamlıköy",
  "Çatalköy",
  "Çayırova",
  "Çayönü",
  "Çınarlı",
  "Çanakkale",
  "Çukurova",
  "Dağyolu",
  "Değirmenlik",
  "Demirhan",
  "Denizli",
  "Derince",
  "Dilekkaya",
  "Dipkarpaz",
  "Doğancı",
  "Doğanköy",
  "Dörtyol",
  "Düzce",
  "Düzova",
  "Edremit",
  "Erdemli",
  "Erenköy",
  "Ergazi",
  "Ergenekon",
  "Esenköy",
  "Esentepe",
  "Gayretköy",
  "Gaziler",
  "Gaziköy",
  "Gazimağusa",
  "Gaziveren",
  "Geçitkale",
  "Geçitköy",
  "Gelincik",
  "Gemikonağı",
  "Girne",
  "Gökhan",
  "Gönendere",
  "Göçeri",
  "Gönyeli",
  "Görneç",
  "Günebakan",
  "Güneşköy",
  "Güngör",
  "Gürpınar",
  "Güvercinlik",
  "Güzelyurt",
  "Hamitköy",
  "Haspolat",
  "Hisarköy",
  "Ilgaz",
  "İkidere",
  "İncesu",
  "İncirli",
  "İnönü",
  "İskele",
  "İskele Bahçeler (Cevizli)",
  "Kalavaç",
  "Kaleburnu",
  "Kalecik",
  "Kalkanlı",
  "Kanlıköy",
  "Kantara",
  "Kaplıca",
  "Karaağaç",
  "Karaman",
  "Karaoğlanoğlu",
  "Karpaşa",
  "Karşıyaka",
  "Kargı",
  "Kayalar",
  "Kılıçaslan",
  "Kilitkaya",
  "Kırıkkale",
  "Kırklar",
  "Korkuteli",
  "Koruçam",
  "Kozan",
  "Köprülü",
  "Kömürcü",
  "Kumyalı",
  "Kurudere",
  "Kuruova",
  "Kurutepe",
  "Kurtuluş",
  "Kuzucuk",
  "Lapta",
  "Lefke",
  "Lefkoşa",
  "Madenliköy",
  "Malatya",
  "Mallıdağ",
  "Mehmetçik",
  "Meriç",
  "Mersinlik",
  "Metehan",
  "Mevlevi",
  "Minareliköy",
  "Mormenekşe",
  "Muratağa",
  "Mutluyaka",
  "Nergisli",
  "Ozanköy",
  "Ömerli",
  "Ötüken",
  "Özhan",
  "Pamuklu",
  "Paşaköy",
  "Pile",
  "Pınarbaşı",
  "Pınarlı",
  "Pirhan",
  "Sadrazamköy",
  "Sandallar",
  "Sazlıköy",
  "Serdarlı",
  "Serhatköy",
  "Sınırüstü",
  "Sipahi",
  "Sütlüce",
  "Şahinler",
  "Şirinevler",
  "Şirinköy",
  "Tatlısu",
  "Taşköy",
  "Taşlıca",
  "Taşpınar",
  "Tepebaşı",
  "Tirmen",
  "Topçuköy",
  "Turnalar",
  "Turunçlu",
  "Tuzla",
  "Tuzluca",
  "Türkeli",
  "Türkmenköy",
  "Ulukışla",
  "Vadili",
  "Yamaçköy",
  "Yarköy",
  "Yayla",
  "Yedidalga",
  "Yedikonuk",
  "Yeni Erenköy",
  "Yeniceköy",
  "Yeniboğaziçi",
  "Yenikent",
  "Yeşilırmak",
  "Yeşilköy",
  "Yeşiltepe",
  "Yeşilyurt",
  "Yıldırım",
  "Yılmazköy",
  "Yiğitler",
  "Yukarı Bostancı",
  "Yukarı Dikmen",
  "Yukarı Taşkent",
  "Yuvacık",
  "Zeybekköy",
  "Zeytinlik",
  "Ziyamet",
  "Zümrütköy",
];

// Helper function to get subregions for a main region
List<String> getSubregions(String mainRegion) {
  return regionHierarchy[mainRegion] ?? [];
}

// Helper function to get the main region for a subregion
String? getMainRegion(String subregion) {
  for (String mainRegion in mainRegions) {
    if (regionHierarchy[mainRegion]?.contains(subregion) == true) {
      return mainRegion;
    }
  }
  return null;
}