// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHWgHHhDR3lj0z80W1cFCn-6nQ4BInEo',
    appId: '1:373622886371:web:027e9925e1726d2a225ad6',
    messagingSenderId: '373622886371',
    projectId: 'emlak-mobile-app',
    authDomain: 'emlak-mobile-app.firebaseapp.com',
    storageBucket: 'emlak-mobile-app.appspot.com',
    measurementId: 'G-FMFKMCC5QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtcymfCon8n2lwYtQlR9yv3G1Ez3tlbA',
    appId: '1:373622886371:android:49911090ac4a7892225ad6',
    messagingSenderId: '373622886371',
    projectId: 'emlak-mobile-app',
    storageBucket: 'emlak-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuWLIn5pC8YFjIEyXezSkvCA_9aIJHyFk',
    appId: '1:373622886371:ios:ab53b97e1e7af143225ad6',
    messagingSenderId: '373622886371',
    projectId: 'emlak-mobile-app',
    storageBucket: 'emlak-mobile-app.appspot.com',
    iosBundleId: 'com.ects.nar24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuWLIn5pC8YFjIEyXezSkvCA_9aIJHyFk',
    appId: '1:373622886371:ios:ab53b97e1e7af143225ad6',
    messagingSenderId: '373622886371',
    projectId: 'emlak-mobile-app',
    storageBucket: 'emlak-mobile-app.appspot.com',
    iosBundleId: 'com.ects.nar24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHWgHHhDR3lj0z80W1cFCn-6nQ4BInEo',
    appId: '1:373622886371:web:ccc361ec5cfbdd49225ad6',
    messagingSenderId: '373622886371',
    projectId: 'emlak-mobile-app',
    authDomain: 'emlak-mobile-app.firebaseapp.com',
    storageBucket: 'emlak-mobile-app.appspot.com',
    measurementId: 'G-6ZYSPJ06C5',
  );

}