// lib/utils/food_localization.dart
//
// Resolves food category / food-type / extra names stored in Firestore
// (English keys) to their localized display strings via AppLocalizations.
//
// Flutter's generated l10n does not support dynamic key lookup, so we
// maintain a mapping from the raw English name to the corresponding
// AppLocalizations getter.

import '../generated/l10n/app_localizations.dart';

/// Localize a food-category name (e.g. "Kebabs & Grills").
String localizeCategory(String raw, AppLocalizations loc) =>
    _cats[raw]?.call(loc) ?? raw;

/// Localize a food-type name (e.g. "Adana Kebab").
String localizeFoodType(String raw, AppLocalizations loc) =>
    _types[raw]?.call(loc) ?? raw;

/// Localize an extra name (e.g. "Extra Cheese").
String localizeExtra(String raw, AppLocalizations loc) =>
    _extras[raw]?.call(loc) ?? raw;

/// Localize a cuisine-type name stored in Firestore (e.g. "Turkish Cuisine").
String localizeCuisineType(String raw, AppLocalizations loc) =>
    _cuisineTypes[raw]?.call(loc) ?? raw;

/// Localize a list of cuisine-type names and join with ", ".
String localizeCuisines(List<String> list, AppLocalizations loc) =>
    list.map((c) => localizeCuisineType(c, loc)).join(', ');

// ─────────────────────────────────────────────────────────────────────────────
// Category resolvers  (24 entries)
// ─────────────────────────────────────────────────────────────────────────────

final _cats = <String, String Function(AppLocalizations)>{
  'Kebabs & Grills': (l) => l.foodCategoryKebabsGrills,
  'Pide & Lahmacun': (l) => l.foodCategoryPideLahmacun,
  'Soups': (l) => l.foodCategorySoups,
  'Salads': (l) => l.foodCategorySalads,
  'Appetizers & Meze': (l) => l.foodCategoryAppetizers,
  'Stews & Casseroles': (l) => l.foodCategoryStews,
  'Dolma & Sarma': (l) => l.foodCategoryDolma,
  'Steak & Roast': (l) => l.foodCategorySteakRoast,
  'Stir Fry & Wok': (l) => l.foodCategoryStirFry,
  'Fried Chicken': (l) => l.foodCategoryFriedChicken,
  'Rice & Pilaf': (l) => l.foodCategoryRicePilaf,
  'Noodles': (l) => l.foodCategoryNoodles,
  'Sushi & Sashimi': (l) => l.foodCategorySushi,
  'Curry': (l) => l.foodCategoryCurry,
  'Pasta': (l) => l.foodCategoryPasta,
  'Wraps': (l) => l.foodCategoryWraps,
  'Doner': (l) => l.foodCategoryDoner,
  'Sandwich & Toast': (l) => l.foodCategorySandwich,
  'Seafood': (l) => l.foodCategorySeafood,
  'Breakfast': (l) => l.foodCategoryBreakfast,
  'Desserts & Pastry': (l) => l.foodCategoryDesserts,
  'Beverages': (l) => l.foodCategoryBeverages,
  'Hamburger': (l) => l.foodCategoryHamburger,
  'Pizza': (l) => l.foodCategoryPizza,
};

// ─────────────────────────────────────────────────────────────────────────────
// Food-type resolvers  (~280 entries)
// ─────────────────────────────────────────────────────────────────────────────

final _types = <String, String Function(AppLocalizations)>{
  // Kebabs & Grills
  'Adana Kebab': (l) => l.foodTypeAdanaKebab,
  'Urfa Kebab': (l) => l.foodTypeUrfaKebab,
  'Iskender Kebab': (l) => l.foodTypeIskenderKebab,
  'Shish Kebab': (l) => l.foodTypeShishKebab,
  'Chicken Kebab': (l) => l.foodTypeChickenKebab,
  'Kofte': (l) => l.foodTypeKofte,
  'Mixed Grill': (l) => l.foodTypeMixedGrill,
  'Lamb Chops': (l) => l.foodTypeLambChops,
  'Beyti Kebab': (l) => l.foodTypeBeytiKebab,
  'Ali Nazik': (l) => l.foodTypeAliNazik,
  'Cop Sis': (l) => l.foodTypeCopSis,
  'Ciğer Kebab': (l) => l.foodTypeCigerKebab,
  'Tantuni': (l) => l.foodTypeTantuni,
  'Patlican Kebab': (l) => l.foodTypePatlicanKebab,
  'Testi Kebab': (l) => l.foodTypeTestiKebab,
  'Cag Kebab': (l) => l.foodTypeCagKebab,
  'Pideli Kofte': (l) => l.foodTypePideliKofte,
  'Kuzu Sis': (l) => l.foodTypeKuzuSis,
  'Orman Kebab': (l) => l.foodTypeOrmanKebab,
  'Yogurtlu Kebab': (l) => l.foodTypeYogurtluKebab,
  'Chelo Kebab': (l) => l.foodTypeCheloKebab,
  'Joojeh Kebab': (l) => l.foodTypeJoojehKebab,
  'Koobideh': (l) => l.foodTypeKoobideh,
  'Bulgogi': (l) => l.foodTypeBulgogi,
  'Galbi': (l) => l.foodTypeGalbi,
  'Samgyeopsal': (l) => l.foodTypeSamgyeopsal,
  'Yakitori': (l) => l.foodTypeYakitori,
  'Tandoori Chicken': (l) => l.foodTypeTandooriChicken,
  'Souvlaki': (l) => l.foodTypeSouvlaki,
  'Gyros': (l) => l.foodTypeGyros,
  'Satay': (l) => l.foodTypeSatay,
  'Kokoreç': (l) => l.foodTypeKokorec,
  'Other Kebab': (l) => l.foodTypeOtherKebab,
  // Pide & Lahmacun
  'Cheese Pide': (l) => l.foodTypeCheesePide,
  'Minced Meat Pide': (l) => l.foodTypeMincedMeatPide,
  'Sucuklu Pide': (l) => l.foodTypeSucukluPide,
  'Kasarli Pide': (l) => l.foodTypeKasarliPide,
  'Kusbasi Pide': (l) => l.foodTypeKusbasiPide,
  'Lahmacun': (l) => l.foodTypeLahmacun,
  'Etli Ekmek': (l) => l.foodTypeEtliEkmek,
  'Yumurtali Pide': (l) => l.foodTypeYumurtaliPide,
  'Ispanakli Pide': (l) => l.foodTypeIspanakliPide,
  'Karisik Pide': (l) => l.foodTypeKarisikPide,
  'Pastirmali Pide': (l) => l.foodTypePastirmaliPide,
  'Other Pide': (l) => l.foodTypeOtherPide,
  // Soups
  'Lentil Soup': (l) => l.foodTypeLentilSoup,
  'Tomato Soup': (l) => l.foodTypeTomatoSoup,
  'Chicken Soup': (l) => l.foodTypeChickenSoup,
  'Tarhana Soup': (l) => l.foodTypeTarhanaSoup,
  'Ezogelin Soup': (l) => l.foodTypeEzogelinSoup,
  'Iskembe Soup': (l) => l.foodTypeIskembeSoup,
  'Yayla Soup': (l) => l.foodTypeYaylaSoup,
  'Mushroom Soup': (l) => l.foodTypeMushroomSoup,
  'Mercimek Soup': (l) => l.foodTypeMercimekSoup,
  'Beyran': (l) => l.foodTypeBeyran,
  'Dugun Corbasi': (l) => l.foodTypeDugunCorbasi,
  'Kellepaca Corbasi': (l) => l.foodTypeKellepacaCorbasi,
  'Sehriye Corbasi': (l) => l.foodTypeSehriyeCorbasi,
  'Lebeniye Corbasi': (l) => l.foodTypeLebeniyeCorbasi,
  'Miso Soup': (l) => l.foodTypeMisoSoup,
  'Wonton Soup': (l) => l.foodTypeWontonSoup,
  'Kimchi Jjigae': (l) => l.foodTypeKimchiJjigae,
  'Sundubu Jjigae': (l) => l.foodTypeSundubuJjigae,
  'Ash Reshteh': (l) => l.foodTypeAshReshteh,
  'Minestrone': (l) => l.foodTypeMinestrone,
  'Tom Yum': (l) => l.foodTypeTomYum,
  'Other Soup': (l) => l.foodTypeOtherSoup,
  // Salads
  'Shepherd Salad': (l) => l.foodTypeShepherdSalad,
  'Caesar Salad': (l) => l.foodTypeCaesarSalad,
  'Greek Salad': (l) => l.foodTypeGreekSalad,
  'Seasonal Salad': (l) => l.foodTypeSeasonalSalad,
  'Rocket Salad': (l) => l.foodTypeRocketSalad,
  'Gavurdagi Salad': (l) => l.foodTypeGavurdagiSalad,
  'Piyaz': (l) => l.foodTypePiyaz,
  'Coban Salad': (l) => l.foodTypeCobanSalad,
  'Kisir': (l) => l.foodTypeKisir,
  'Semizotu Salatasi': (l) => l.foodTypeSemizotuSalatasi,
  'Mor Lahana Salatasi': (l) => l.foodTypeMorLahanaSalatasi,
  'Fattoush': (l) => l.foodTypeFattoush,
  'Tabbouleh': (l) => l.foodTypeTabbouleh,
  'Caprese': (l) => l.foodTypeCaprese,
  'Other Salad': (l) => l.foodTypeOtherSalad,
  // Appetizers & Meze
  'Hummus': (l) => l.foodTypeHummus,
  'Babaganoush': (l) => l.foodTypeBabaganoush,
  'Haydari': (l) => l.foodTypeHaydari,
  'Atom': (l) => l.foodTypeAtom,
  'Acili Ezme': (l) => l.foodTypeAciliEzme,
  'Cacik': (l) => l.foodTypeCacik,
  'Sigara Boregi': (l) => l.foodTypeSigaraBoregi,
  'Icli Kofte': (l) => l.foodTypeIcliKofte,
  'Mercimek Kofte': (l) => l.foodTypeMercimekKofte,
  'Yaprak Sarma': (l) => l.foodTypeYaprakSarma,
  'Falafel': (l) => l.foodTypeFalafel,
  'Mucver': (l) => l.foodTypeMucver,
  'Patlican Soslu': (l) => l.foodTypePatlicanSoslu,
  'Cig Kofte': (l) => l.foodTypeCigKofte,
  'Arnavut Cigeri': (l) => l.foodTypeArnavutCigeri,
  'Cerkez Tavugu': (l) => l.foodTypeCerkezTavugu,
  'Tarator': (l) => l.foodTypeTarator,
  'Borek': (l) => l.foodTypeBorek,
  'Su Boregi': (l) => l.foodTypeSuBoregi,
  'Dim Sum': (l) => l.foodTypeDimSum,
  'Spring Rolls': (l) => l.foodTypeSpringRolls,
  'Dumplings': (l) => l.foodTypeDumplings,
  'Gyoza': (l) => l.foodTypeGyoza,
  'Edamame': (l) => l.foodTypeEdamame,
  'Tempura': (l) => l.foodTypeTempura,
  'Takoyaki': (l) => l.foodTypeTakoyaki,
  'Bruschetta': (l) => l.foodTypeBruschetta,
  'Arancini': (l) => l.foodTypeArancini,
  'Carpaccio': (l) => l.foodTypeCarpaccio,
  'Focaccia': (l) => l.foodTypeFocaccia,
  'Kibbeh': (l) => l.foodTypeKibbeh,
  'Moutabal': (l) => l.foodTypeMoutabal,
  'Mirza Ghasemi': (l) => l.foodTypeMirzaGhasemi,
  'Kashk-e Bademjan': (l) => l.foodTypeKashkBademjan,
  'Pajeon': (l) => l.foodTypePajeon,
  'Samosa': (l) => l.foodTypeSamosa,
  'Nachos': (l) => l.foodTypeNachos,
  'Other Meze': (l) => l.foodTypeOtherMeze,
  // Stews & Casseroles
  'Guvec': (l) => l.foodTypeGuvec,
  'Moussaka': (l) => l.foodTypeMoussaka,
  'Hunkar Begendi': (l) => l.foodTypeHunkarBegendi,
  'Etli Nohut': (l) => l.foodTypeEtliNohut,
  'Turlu': (l) => l.foodTypeTurlu,
  'Taze Fasulye': (l) => l.foodTypeTazeFasulye,
  'Etli Bamya': (l) => l.foodTypeEtliBamya,
  'Etli Bezelye': (l) => l.foodTypeEtliBezelye,
  'Etli Kapuska': (l) => l.foodTypeEtliKapuska,
  'Ispanak Yemegi': (l) => l.foodTypeIspanakYemegi,
  'Etli Pirasa': (l) => l.foodTypeEtliPirasa,
  'Kuru Fasulye': (l) => l.foodTypeKuruFasulye,
  'Barbunya': (l) => l.foodTypeBarbunya,
  'Nohut Yemegi': (l) => l.foodTypeNohutYemegi,
  'Zeytinyagli Enginar': (l) => l.foodTypeZeytinyagliEnginar,
  'Ghormeh Sabzi': (l) => l.foodTypeGhormehSabzi,
  'Fesenjan': (l) => l.foodTypeFesenjan,
  'Dizi Abgoosht': (l) => l.foodTypeDiziAbgoosht,
  'Hot Pot': (l) => l.foodTypeHotPot,
  'Mansaf': (l) => l.foodTypeMansaf,
  'Fatteh': (l) => l.foodTypeFatteh,
  'Maqluba': (l) => l.foodTypeMaqluba,
  'Shakshuka': (l) => l.foodTypeShakshuka,
  'Tteokbokki': (l) => l.foodTypeTteokbokki,
  'Osso Buco': (l) => l.foodTypeOssoBuco,
  'Kuzu Incik': (l) => l.foodTypeKuzuIncik,
  'Other Stew': (l) => l.foodTypeOtherStew,
  // Dolma & Sarma
  'Imam Bayildi': (l) => l.foodTypeImamBayildi,
  'Karniyarik': (l) => l.foodTypeKarniyarik,
  'Lahana Sarma': (l) => l.foodTypeLahanaSarma,
  'Kabak Dolma': (l) => l.foodTypeKabakDolma,
  'Patlican Dolma': (l) => l.foodTypePatlicanDolma,
  'Biber Dolma': (l) => l.foodTypeBiberDolma,
  'Etli Yaprak Sarma': (l) => l.foodTypeEtliYaprakSarma,
  'Zeytinyagli Dolma': (l) => l.foodTypeZeytinyagliDolma,
  'Stuffed Peppers': (l) => l.foodTypeStuffedPeppers,
  'Mahshi': (l) => l.foodTypeMahshi,
  'Other Dolma': (l) => l.foodTypeOtherDolma,
  // Steak & Roast
  'Steak': (l) => l.foodTypeSteak,
  'Kuzu Tandir': (l) => l.foodTypeKuzuTandir,
  'Sac Kavurma': (l) => l.foodTypeSacKavurma,
  'Tas Kebab': (l) => l.foodTypeTasKebab,
  'Peking Duck': (l) => l.foodTypePekingDuck,
  'Saltimbocca': (l) => l.foodTypeSaltimbocca,
  'Other Steak': (l) => l.foodTypeOtherSteak,
  // Stir Fry & Wok
  'Kung Pao Chicken': (l) => l.foodTypeKungPaoChicken,
  'Sweet and Sour Chicken': (l) => l.foodTypeSweetSourChicken,
  'Mapo Tofu': (l) => l.foodTypeMapoTofu,
  'Teriyaki': (l) => l.foodTypeTeriyaki,
  'Dakgalbi': (l) => l.foodTypeDakgalbi,
  'Other Stir Fry': (l) => l.foodTypeOtherStirFry,
  // Fried Chicken
  'Fried Chicken Classic': (l) => l.foodTypeFriedChickenClassic,
  'Korean Fried Chicken': (l) => l.foodTypeKoreanFriedChicken,
  'Chicken Schnitzel': (l) => l.foodTypeChickenSchnitzel,
  'Tonkatsu': (l) => l.foodTypeTonkatsu,
  'Chicken Wings': (l) => l.foodTypeChickenWings,
  'Chicken Tenders': (l) => l.foodTypeChickenTenders,
  'Nuggets': (l) => l.foodTypeNuggets,
  'Other Fried Chicken': (l) => l.foodTypeOtherFriedChicken,
  // Rice & Pilaf
  'Bulgur Pilaf': (l) => l.foodTypeBulgurPilaf,
  'Rice Pilaf': (l) => l.foodTypeRicePilaf,
  'Nohutlu Pilav': (l) => l.foodTypeNohutluPilav,
  'Ic Pilav': (l) => l.foodTypeIcPilav,
  'Domatesli Bulgur': (l) => l.foodTypeDomatesliB,
  'Firik Pilavi': (l) => l.foodTypeFirikPilavi,
  'Sebzeli Pilav': (l) => l.foodTypeSebzeliPilav,
  'Meyhane Pilavi': (l) => l.foodTypeMeyhanePilavi,
  'Fried Rice': (l) => l.foodTypeFriedRice,
  'Bibimbap': (l) => l.foodTypeBibimbap,
  'Donburi': (l) => l.foodTypeDonburi,
  'Tahdig': (l) => l.foodTypeTahdig,
  'Tahchin': (l) => l.foodTypeTahchin,
  'Zereshk Polo': (l) => l.foodTypeZereshkPolo,
  'Baghali Polo': (l) => l.foodTypeBaghaliPolo,
  'Sabzi Polo': (l) => l.foodTypeSabziPolo,
  'Kabsa': (l) => l.foodTypeKabsa,
  'Machboos': (l) => l.foodTypeMachboos,
  'Biryani': (l) => l.foodTypeBiryani,
  'Hamsili Pilav': (l) => l.foodTypeHamsiliPilav,
  'Ali Pasa Pilavi': (l) => l.foodTypeAliPasaPilavi,
  'Other Pilaf': (l) => l.foodTypeOtherPilaf,
  // Noodles
  'Ramen': (l) => l.foodTypeRamen,
  'Udon': (l) => l.foodTypeUdon,
  'Soba': (l) => l.foodTypeSoba,
  'Pho': (l) => l.foodTypePho,
  'Pad Thai': (l) => l.foodTypePadThai,
  'Chow Mein': (l) => l.foodTypeChowMein,
  'Dan Dan Noodles': (l) => l.foodTypeDanDanNoodles,
  'Japchae': (l) => l.foodTypeJapchae,
  'Jajangmyeon': (l) => l.foodTypeJajangmyeon,
  'Naengmyeon': (l) => l.foodTypeNaengmyeon,
  'Other Noodle': (l) => l.foodTypeOtherNoodle,
  // Sushi & Sashimi
  'Sushi': (l) => l.foodTypeSushi,
  'Sashimi': (l) => l.foodTypeSashimi,
  'Maki Roll': (l) => l.foodTypeMakiRoll,
  'Nigiri': (l) => l.foodTypeNigiri,
  'Temaki': (l) => l.foodTypeTemaki,
  'Onigiri': (l) => l.foodTypeOnigiri,
  'Kimbap': (l) => l.foodTypeKimbap,
  'Other Sushi': (l) => l.foodTypeOtherSushi,
  // Curry
  'Katsu Curry': (l) => l.foodTypeKatsuCurry,
  'Butter Chicken': (l) => l.foodTypeButterChicken,
  'Tikka Masala': (l) => l.foodTypeTikkaMasala,
  'Green Curry': (l) => l.foodTypeGreenCurry,
  'Red Curry': (l) => l.foodTypeRedCurry,
  'Massaman Curry': (l) => l.foodTypeMassamanCurry,
  'Dal': (l) => l.foodTypeDal,
  'Vindaloo': (l) => l.foodTypeVindaloo,
  'Other Curry': (l) => l.foodTypeOtherCurry,
  // Pasta
  'Spaghetti Bolognese': (l) => l.foodTypeSpagBolognese,
  'Penne Arrabiata': (l) => l.foodTypePenneArrabiata,
  'Fettuccine Alfredo': (l) => l.foodTypeFettuccineAlfredo,
  'Lasagna': (l) => l.foodTypeLasagna,
  'Makarna': (l) => l.foodTypeMakarna,
  'Carbonara': (l) => l.foodTypeCarbonara,
  'Ravioli': (l) => l.foodTypeRavioli,
  'Risotto': (l) => l.foodTypeRisotto,
  'Gnocchi': (l) => l.foodTypeGnocchi,
  'Manti': (l) => l.foodTypeManti,
  'Other Pasta': (l) => l.foodTypeOtherPasta,
  // Wraps
  'Doner Wrap': (l) => l.foodTypeDonerWrap,
  'Tavuk Durum': (l) => l.foodTypeTavukDurum,
  'Et Durum': (l) => l.foodTypeEtDurum,
  'Cig Kofte Durum': (l) => l.foodTypeCigKofteDurum,
  'Adana Durum': (l) => l.foodTypeAdanaDurum,
  'Midye Durum': (l) => l.foodTypeMidyeDurum,
  'Tacos': (l) => l.foodTypeTacos,
  'Burrito': (l) => l.foodTypeBurrito,
  'Quesadilla': (l) => l.foodTypeQuesadilla,
  'Other Wrap': (l) => l.foodTypeOtherWrap,
  // Doner
  'Chicken Doner': (l) => l.foodTypeChickenDoner,
  'Meat Doner': (l) => l.foodTypeMeatDoner,
  'Iskender Doner': (l) => l.foodTypeIskenderDoner,
  'Tombik Doner': (l) => l.foodTypeTombikDoner,
  'Porsiyon Doner': (l) => l.foodTypePorsiyonDoner,
  'Shawarma': (l) => l.foodTypeShawarma,
  'Other Doner': (l) => l.foodTypeOtherDoner,
  // Sandwich & Toast
  'Tost': (l) => l.foodTypeTost,
  'Kasarli Tost': (l) => l.foodTypeKasarliTost,
  'Kumru': (l) => l.foodTypeKumru,
  'Club Sandwich': (l) => l.foodTypeClubSandwich,
  'Panini': (l) => l.foodTypePanini,
  'Hot Dog': (l) => l.foodTypeHotDog,
  'French Fries': (l) => l.foodTypeFrenchFries,
  'Other Sandwich': (l) => l.foodTypeOtherSandwich,
  // Seafood
  'Grilled Fish': (l) => l.foodTypeGrilledFish,
  'Fried Calamari': (l) => l.foodTypeFriedCalamari,
  'Shrimp Casserole': (l) => l.foodTypeShrimpCasserole,
  'Fish Sandwich': (l) => l.foodTypeFishSandwich,
  'Levrek': (l) => l.foodTypeLevrek,
  'Somon': (l) => l.foodTypeSomon,
  'Hamsi': (l) => l.foodTypeHamsi,
  'Midye Tava': (l) => l.foodTypeMidyeTava,
  'Midye Dolma': (l) => l.foodTypeMidyeDolma,
  'Karides Guvec': (l) => l.foodTypeKaridesGuvec,
  'Palamut': (l) => l.foodTypePalamut,
  'Cipura': (l) => l.foodTypeCipura,
  'Barbun Tava': (l) => l.foodTypeBarbunTava,
  'Lufer': (l) => l.foodTypeLufer,
  'Fish and Chips': (l) => l.foodTypeFishAndChips,
  'Other Seafood': (l) => l.foodTypeOtherSeafood,
  // Breakfast
  'Turkish Breakfast Plate': (l) => l.foodTypeTurkishBreakfast,
  'Serpme Kahvalti': (l) => l.foodTypeSerpmeKahvalti,
  'Menemen': (l) => l.foodTypeMenemen,
  'Sahanda Yumurta': (l) => l.foodTypeSahandaYumurta,
  'Sucuklu Yumurta': (l) => l.foodTypeSucukluYumurta,
  'Gozleme': (l) => l.foodTypeGozleme,
  'Simit': (l) => l.foodTypeSimit,
  'Acma': (l) => l.foodTypeAcma,
  'Pogaca': (l) => l.foodTypePogaca,
  'Cilbir': (l) => l.foodTypeCilbir,
  'Pastirmali Yumurta': (l) => l.foodTypePastirmaliYumurta,
  'Kaymak Bal': (l) => l.foodTypeKaymakBal,
  'Pisi': (l) => l.foodTypePisi,
  'Katmer Kahvalti': (l) => l.foodTypeKatmerKahvalti,
  'Other Breakfast': (l) => l.foodTypeOtherBreakfast,
  // Desserts & Pastry
  'Baklava': (l) => l.foodTypeBaklava,
  'Kunefe': (l) => l.foodTypeKunefe,
  'Sutlac': (l) => l.foodTypeSutlac,
  'Kazandibi': (l) => l.foodTypeKazandibi,
  'Tavuk Gogsu': (l) => l.foodTypeTavukGogsu,
  'Asure': (l) => l.foodTypeAsure,
  'Revani': (l) => l.foodTypeRevani,
  'Lokma': (l) => l.foodTypeLokma,
  'Trilece': (l) => l.foodTypeTrilece,
  'Profiterol': (l) => l.foodTypeProfiterol,
  'Cheesecake': (l) => l.foodTypeCheesecake,
  'Tiramisu': (l) => l.foodTypeTiramisu,
  'Brownie': (l) => l.foodTypeBrownie,
  'Waffle': (l) => l.foodTypeWaffle,
  'Dondurma': (l) => l.foodTypeDondurma,
  'Gullac': (l) => l.foodTypeGullac,
  'Keskul': (l) => l.foodTypeKeskul,
  'Tel Kadayif': (l) => l.foodTypeTelKadayif,
  'Sekerpare': (l) => l.foodTypeSekerpare,
  'Tulumba': (l) => l.foodTypeTulumba,
  'Helva': (l) => l.foodTypeHelva,
  'Katmer': (l) => l.foodTypeKatmer,
  'Kabak Tatlisi': (l) => l.foodTypeKabakTatlisi,
  'Ayva Tatlisi': (l) => l.foodTypeAyvaTatlisi,
  'Sutlu Nuriye': (l) => l.foodTypeSutluNuriye,
  'Burma Kadayif': (l) => l.foodTypeBurmaKadayif,
  'Panna Cotta': (l) => l.foodTypePannaCotta,
  'Gelato': (l) => l.foodTypeGelato,
  'Cannoli': (l) => l.foodTypeCannoli,
  'Knafeh': (l) => l.foodTypeKnafeh,
  'Muhallabia': (l) => l.foodTypeMuhallabia,
  'Churros': (l) => l.foodTypeChurros,
  'Mochi': (l) => l.foodTypeMochi,
  'Other Dessert': (l) => l.foodTypeOtherDessert,
  // Beverages
  'Turkish Tea': (l) => l.foodTypeTurkishTea,
  'Turkish Coffee': (l) => l.foodTypeTurkishCoffee,
  'Ayran': (l) => l.foodTypeAyran,
  'Fresh Orange Juice': (l) => l.foodTypeFreshOrangeJuice,
  'Lemonade': (l) => l.foodTypeLemonade,
  'Smoothie': (l) => l.foodTypeSmoothie,
  'Salgam': (l) => l.foodTypeSalgam,
  'Boza': (l) => l.foodTypeBoza,
  'Sahlep': (l) => l.foodTypeSahlep,
  'Soft Drink': (l) => l.foodTypeSoftDrink,
  'Water': (l) => l.foodTypeWater,
  'Nar Suyu': (l) => l.foodTypeNarSuyu,
  'Serbet': (l) => l.foodTypeSerbet,
  'Turk Kahvesi Soguk': (l) => l.foodTypeTurkKahvesiSoguk,
  'Other Beverage': (l) => l.foodTypeOtherBeverage,
  // Hamburger
  'Hamburger': (l) => l.foodTypeHamburger,
  'Cheeseburger': (l) => l.foodTypeCheeseburger,
  'Chicken Burger': (l) => l.foodTypeChickenBurger,
  'Islak Hamburger': (l) => l.foodTypeIslakHamburger,
  'Veggie Burger': (l) => l.foodTypeVeggieBurger,
  'Other Hamburger': (l) => l.foodTypeOtherHamburger,
  // Pizza
  'Margarita Pizza': (l) => l.foodTypeMargaritaPizza,
  'Mixed Pizza': (l) => l.foodTypeMixedPizza,
  'Pepperoni Pizza': (l) => l.foodTypePepperoniPizza,
  'Sucuklu Pizza': (l) => l.foodTypeSucukluPizza,
  'Four Cheese Pizza': (l) => l.foodTypeFourCheesePizza,
  'Other Pizza': (l) => l.foodTypeOtherPizza,
};

// ─────────────────────────────────────────────────────────────────────────────
// Extra resolvers  (~90 entries)
// ─────────────────────────────────────────────────────────────────────────────

final _extras = <String, String Function(AppLocalizations)>{
  // Bread & Carbs
  'Extra Bread': (l) => l.foodExtraBread,
  'Rice Portion': (l) => l.foodExtraRicePortion,
  'Bulgur Portion': (l) => l.foodExtraBulgurPortion,
  'Extra Rice': (l) => l.foodExtraRice,
  'Garlic Bread': (l) => l.foodExtraGarlicBread,
  'Lavash': (l) => l.foodExtraLavash,
  'Simit Side': (l) => l.foodExtraSimiSide,
  'Pita Chips': (l) => l.foodExtraPitaChips,
  'Croutons': (l) => l.foodExtraCroutons,
  // Dairy & Eggs
  'Extra Cheese': (l) => l.foodExtraCheese,
  'Parmesan': (l) => l.foodExtraParmesan,
  'Yogurt': (l) => l.foodExtraYogurt,
  'Butter': (l) => l.foodExtraButter,
  'Feta Cheese': (l) => l.foodExtraFetaCheese,
  'Extra Egg': (l) => l.foodExtraEgg,
  'Kaymak Portion': (l) => l.foodExtraKaymakPortion,
  'Milk': (l) => l.foodExtraMilk,
  'Saffron Butter': (l) => l.foodExtraSaffronButter,
  'Cream Sauce Extra': (l) => l.foodExtraCreamSauce,
  // Sauces & Condiments
  'Garlic Sauce': (l) => l.foodExtraGarlicSauce,
  'Ketchup': (l) => l.foodExtraKetchup,
  'Mayonnaise': (l) => l.foodExtraMayonnaise,
  'Mustard': (l) => l.foodExtraMustard,
  'Soy Sauce': (l) => l.foodExtraSoySauce,
  'Tartar Sauce': (l) => l.foodExtraTartarSauce,
  'Sweet Chili Sauce': (l) => l.foodExtraSweetChiliSauce,
  'Teriyaki Sauce': (l) => l.foodExtraTeriyakiSauce,
  'Gochujang Sauce': (l) => l.foodExtraGochujangSauce,
  'Balsamic Glaze': (l) => l.foodExtraBalsamicGlaze,
  'Truffle Oil': (l) => l.foodExtraTruffleOil,
  'Chili Oil': (l) => l.foodExtraChiliOil,
  'Hot Mustard': (l) => l.foodExtraHotMustard,
  'Sesame Oil': (l) => l.foodExtraSesameOil,
  'Chocolate Sauce': (l) => l.foodExtraChocolateSauce,
  'Extra Syrup': (l) => l.foodExtraExtraSyrup,
  'Pomegranate Syrup': (l) => l.foodExtraPomegranateSyrup,
  'Tahini': (l) => l.foodExtraTahini,
  'Extra Dressing': (l) => l.foodExtraExtraDressing,
  'Extra Sugar': (l) => l.foodExtraExtraSugar,
  // Vegetables & Toppings
  'Grilled Vegetables': (l) => l.foodExtraGrilledVegetables,
  'Grilled Chicken': (l) => l.foodExtraGrilledChicken,
  'Hot Pepper': (l) => l.foodExtraHotPepper,
  'Onion Salad': (l) => l.foodExtraOnionSalad,
  'Sumac Onion': (l) => l.foodExtraSumacOnion,
  'Parsley': (l) => l.foodExtraParsley,
  'Lemon': (l) => l.foodExtraLemon,
  'Corn': (l) => l.foodExtraCorn,
  'Jalapeno': (l) => l.foodExtraJalapeno,
  'Avocado': (l) => l.foodExtraAvocado,
  'Pickles': (l) => l.foodExtraPickles,
  'Mushroom Topping': (l) => l.foodExtraMushroomTopping,
  'Olive Topping': (l) => l.foodExtraOliveTopping,
  'Onion Topping': (l) => l.foodExtraOnionTopping,
  'Pepperoni Topping': (l) => l.foodExtraPepperoniTopping,
  'Sucuk Topping': (l) => l.foodExtraSucukTopping,
  'Green Pepper Topping': (l) => l.foodExtraGreenPepperTopping,
  'Tomato Slices': (l) => l.foodExtraTomatoSlices,
  'Grilled Tomato': (l) => l.foodExtraGrilledTomato,
  'Fresh Herbs': (l) => l.foodExtraFreshHerbs,
  'Steamed Vegetables': (l) => l.foodExtraSteamedVegetables,
  'Mint Leaves': (l) => l.foodExtraMintLeaves,
  'Fresh Fruits': (l) => l.foodExtraFreshFruits,
  'Arugula Side': (l) => l.foodExtraArugulaSide,
  // Sides
  'French Fries Side': (l) => l.foodExtraFrenchFriesSide,
  'Onion Rings': (l) => l.foodExtraOnionRings,
  'Salad Side': (l) => l.foodExtraSaladSide,
  'Chicken Side': (l) => l.foodExtraChickenSide,
  'Edamame Side': (l) => l.foodExtraEdamameSide,
  'Miso Soup Side': (l) => l.foodExtraMisoSoupSide,
  'Spring Roll Side': (l) => l.foodExtraSpringRollSide,
  'Hummus Side': (l) => l.foodExtraHummusSide,
  'Bruschetta Side': (l) => l.foodExtraBruschettaSide,
  'Fattoush Side': (l) => l.foodExtraFattoushSide,
  'Seaweed Salad': (l) => l.foodExtraSeaweedSalad,
  'Glass Noodles Side': (l) => l.foodExtraGlassNoodlesSide,
  'Doogh Side': (l) => l.foodExtraDooghSide,
  'Egg Fried Rice Side': (l) => l.foodExtraEggFriedRiceSide,
  'Kimchi Side': (l) => l.foodExtraKimchiSide,
  'Pickled Radish': (l) => l.foodExtraPickledRadish,
  'Pickled Ginger': (l) => l.foodExtraPickledGinger,
  'Pickled Garlic': (l) => l.foodExtraPickledGarlic,
  'Prawn Crackers': (l) => l.foodExtraPrawnCrackers,
  // Toppings & Extras
  'Extra Meat': (l) => l.foodExtraExtraMeat,
  'Egg Topping': (l) => l.foodExtraEggTopping,
  'Cheese Topping': (l) => l.foodExtraCheeseTopping,
  'Prosciutto Topping': (l) => l.foodExtraProsciuttoTopping,
  'Pistachio Topping': (l) => l.foodExtraPistachioTopping,
  'Tempura Bits': (l) => l.foodExtraTempuraBits,
  'Wasabi': (l) => l.foodExtraWasabi,
  'Tofu Extra': (l) => l.foodExtraTofuExtra,
  'Nutritional Yeast': (l) => l.foodExtraNutritionalYeast,
  'Chickpea Topping': (l) => l.foodExtraChickpeaTopping,
  // Spreads & Portions
  'Honey Portion': (l) => l.foodExtraHoneyPortion,
  'Olive Portion': (l) => l.foodExtraOlivePortion,
  'Jam Portion': (l) => l.foodExtraJamPortion,
  'Olive Oil': (l) => l.foodExtraOliveOil,
  'Ayran Side': (l) => l.foodExtraAyranSide,
  'Tea Glass': (l) => l.foodExtraTeaGlass,
  'Walnut': (l) => l.foodExtraWalnut,
  'Dried Fruits': (l) => l.foodExtraDriedFruits,
  'Sumac': (l) => l.foodExtraSumac,
  // Spices & Seasonings
  'Chili Flakes': (l) => l.foodExtraChiliFlakes,
  'Dried Mint': (l) => l.foodExtraDriedMint,
  'Vinegar': (l) => l.foodExtraVinegar,
  // Dessert / Sweets
  'Ice Cream Scoop': (l) => l.foodExtraIceCreamScoop,
  'Whipped Cream': (l) => l.foodExtraWhippedCream,
  'Ice': (l) => l.foodExtraIce,
};

// ─────────────────────────────────────────────────────────────────────────────
// Cuisine-type resolvers  (maps Firestore English value → localized string)
// ─────────────────────────────────────────────────────────────────────────────

final _cuisineTypes = <String, String Function(AppLocalizations)>{
  'Turkish Cuisine': (l) => l.cuisineTypeTurkish,
  'Japanese Cuisine': (l) => l.cuisineTypeJapanese,
  'Chinese Cuisine': (l) => l.cuisineTypeChinese,
  'Persian Cuisine': (l) => l.cuisineTypePersian,
  'Arabic Cuisine': (l) => l.cuisineTypeArabic,
  'Italian Cuisine': (l) => l.cuisineTypeItalian,
  'Korean Cuisine': (l) => l.cuisineTypeKorean,
  'Vietnamese Cuisine': (l) => l.cuisineTypeVietnamese,
  'Vegan / Vegetarian': (l) => l.cuisineTypeVeganVegetarian,
};
